### ISSUE TITLE
`libdimentio0` is not installable.

### ISSUE THREAD

**Issue by CRKatri** [ProcursusTeam/Procursus#808]
It depends on libkernrw or libkrw, neither of which are installable. I am using checkra1n and only have the Procursus repo, I’d prefer not to add more repos.

**Comment by TheRealKeto** [comment]
libkrw (as well as libkernrw) should be provided by your jailbreak (e.g the Odyssey repo, on coolstar-based jailbreaks, provides this package), in which case, the only issue here is likely the ID of the package, which is incorrectly referenced. I can submit a PR in a few minutes.

**Comment by CRKatri** [comment]
I don’t have the odyssey repo, and the ID is `org.coolstar.libkernrw` which I assume is correct.

**Comment by CRKatri** [comment]
I’d also prefer to use `libkrw`, cause it’s free software, but I’m not sure where to get it, the readme says bingner’s repo, but I’m not using elu.

**Comment by TheRealKeto** [comment]
I see no issue here then; you should have the Odyssey repository, as specific jailbreaks which (currently) use Procursus provide this package... "we" have no control over that. You can ask your specific package maintainer, since providing this package ourselves isn't ideal, considering that each "version" of it is different from each jailbreak.

**Comment by CRKatri** [comment]
On checkra1n either will work, correct?

**Comment by TheRealKeto** [comment]
I believe so.

**Comment by Diatrus** [comment]
Not really valid. In any supported configuration, these packages are installable.
